// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6EFcZpkDeY2beDsqrz7rhNwQK7RCFn2Q',
    appId: '1:1098827157474:android:4cc0d5db00c9aa58eeb3bb',
    messagingSenderId: '1098827157474',
    projectId: 'harmoni-c41f2',
    storageBucket: 'harmoni-c41f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8SZ_XpLiPvU59gKwPpjpCYjeHrH873UQ',
    appId: '1:1098827157474:ios:eaa46a637c55c309eeb3bb',
    messagingSenderId: '1098827157474',
    projectId: 'harmoni-c41f2',
    storageBucket: 'harmoni-c41f2.firebasestorage.app',
    androidClientId: '1098827157474-3rsp1569u4tu0o6mbais9c18sp4svgf8.apps.googleusercontent.com',
    iosClientId: '1098827157474-pjdd9si3j1at01ijhqn8vhhadtt554r6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
